// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package command

import (
	fmt "fmt"
	actor "github.com/AsynkronIT/protoactor-go/actor"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadVertex struct {
	PartitionId          uint64   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	VertexId             string   `protobuf:"bytes,2,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadVertex) Reset()         { *m = LoadVertex{} }
func (m *LoadVertex) String() string { return proto.CompactTextString(m) }
func (*LoadVertex) ProtoMessage()    {}
func (*LoadVertex) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *LoadVertex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadVertex.Unmarshal(m, b)
}
func (m *LoadVertex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadVertex.Marshal(b, m, deterministic)
}
func (m *LoadVertex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadVertex.Merge(m, src)
}
func (m *LoadVertex) XXX_Size() int {
	return xxx_messageInfo_LoadVertex.Size(m)
}
func (m *LoadVertex) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadVertex.DiscardUnknown(m)
}

var xxx_messageInfo_LoadVertex proto.InternalMessageInfo

func (m *LoadVertex) GetPartitionId() uint64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *LoadVertex) GetVertexId() string {
	if m != nil {
		return m.VertexId
	}
	return ""
}

type LoadVertexAck struct {
	PartitionId          uint64   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	VertexId             string   `protobuf:"bytes,2,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadVertexAck) Reset()         { *m = LoadVertexAck{} }
func (m *LoadVertexAck) String() string { return proto.CompactTextString(m) }
func (*LoadVertexAck) ProtoMessage()    {}
func (*LoadVertexAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{1}
}

func (m *LoadVertexAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadVertexAck.Unmarshal(m, b)
}
func (m *LoadVertexAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadVertexAck.Marshal(b, m, deterministic)
}
func (m *LoadVertexAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadVertexAck.Merge(m, src)
}
func (m *LoadVertexAck) XXX_Size() int {
	return xxx_messageInfo_LoadVertexAck.Size(m)
}
func (m *LoadVertexAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadVertexAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoadVertexAck proto.InternalMessageInfo

func (m *LoadVertexAck) GetPartitionId() uint64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *LoadVertexAck) GetVertexId() string {
	if m != nil {
		return m.VertexId
	}
	return ""
}

type SuperStepBarrier struct {
	ClusterInfo          *ClusterInfo `protobuf:"bytes,1,opt,name=clusterInfo,proto3" json:"clusterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SuperStepBarrier) Reset()         { *m = SuperStepBarrier{} }
func (m *SuperStepBarrier) String() string { return proto.CompactTextString(m) }
func (*SuperStepBarrier) ProtoMessage()    {}
func (*SuperStepBarrier) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{2}
}

func (m *SuperStepBarrier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperStepBarrier.Unmarshal(m, b)
}
func (m *SuperStepBarrier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperStepBarrier.Marshal(b, m, deterministic)
}
func (m *SuperStepBarrier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperStepBarrier.Merge(m, src)
}
func (m *SuperStepBarrier) XXX_Size() int {
	return xxx_messageInfo_SuperStepBarrier.Size(m)
}
func (m *SuperStepBarrier) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperStepBarrier.DiscardUnknown(m)
}

var xxx_messageInfo_SuperStepBarrier proto.InternalMessageInfo

func (m *SuperStepBarrier) GetClusterInfo() *ClusterInfo {
	if m != nil {
		return m.ClusterInfo
	}
	return nil
}

type SuperStepBarrierAck struct {
	VertexId             string   `protobuf:"bytes,1,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperStepBarrierAck) Reset()         { *m = SuperStepBarrierAck{} }
func (m *SuperStepBarrierAck) String() string { return proto.CompactTextString(m) }
func (*SuperStepBarrierAck) ProtoMessage()    {}
func (*SuperStepBarrierAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{3}
}

func (m *SuperStepBarrierAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperStepBarrierAck.Unmarshal(m, b)
}
func (m *SuperStepBarrierAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperStepBarrierAck.Marshal(b, m, deterministic)
}
func (m *SuperStepBarrierAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperStepBarrierAck.Merge(m, src)
}
func (m *SuperStepBarrierAck) XXX_Size() int {
	return xxx_messageInfo_SuperStepBarrierAck.Size(m)
}
func (m *SuperStepBarrierAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperStepBarrierAck.DiscardUnknown(m)
}

var xxx_messageInfo_SuperStepBarrierAck proto.InternalMessageInfo

func (m *SuperStepBarrierAck) GetVertexId() string {
	if m != nil {
		return m.VertexId
	}
	return ""
}

type SuperStepBarrierPartitionAck struct {
	PartitionId          uint64   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperStepBarrierPartitionAck) Reset()         { *m = SuperStepBarrierPartitionAck{} }
func (m *SuperStepBarrierPartitionAck) String() string { return proto.CompactTextString(m) }
func (*SuperStepBarrierPartitionAck) ProtoMessage()    {}
func (*SuperStepBarrierPartitionAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{4}
}

func (m *SuperStepBarrierPartitionAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperStepBarrierPartitionAck.Unmarshal(m, b)
}
func (m *SuperStepBarrierPartitionAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperStepBarrierPartitionAck.Marshal(b, m, deterministic)
}
func (m *SuperStepBarrierPartitionAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperStepBarrierPartitionAck.Merge(m, src)
}
func (m *SuperStepBarrierPartitionAck) XXX_Size() int {
	return xxx_messageInfo_SuperStepBarrierPartitionAck.Size(m)
}
func (m *SuperStepBarrierPartitionAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperStepBarrierPartitionAck.DiscardUnknown(m)
}

var xxx_messageInfo_SuperStepBarrierPartitionAck proto.InternalMessageInfo

func (m *SuperStepBarrierPartitionAck) GetPartitionId() uint64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

type SuperStepBarrierWorkerAck struct {
	WorkerPid            *actor.PID `protobuf:"bytes,1,opt,name=worker_pid,json=workerPid,proto3" json:"worker_pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SuperStepBarrierWorkerAck) Reset()         { *m = SuperStepBarrierWorkerAck{} }
func (m *SuperStepBarrierWorkerAck) String() string { return proto.CompactTextString(m) }
func (*SuperStepBarrierWorkerAck) ProtoMessage()    {}
func (*SuperStepBarrierWorkerAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{5}
}

func (m *SuperStepBarrierWorkerAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperStepBarrierWorkerAck.Unmarshal(m, b)
}
func (m *SuperStepBarrierWorkerAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperStepBarrierWorkerAck.Marshal(b, m, deterministic)
}
func (m *SuperStepBarrierWorkerAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperStepBarrierWorkerAck.Merge(m, src)
}
func (m *SuperStepBarrierWorkerAck) XXX_Size() int {
	return xxx_messageInfo_SuperStepBarrierWorkerAck.Size(m)
}
func (m *SuperStepBarrierWorkerAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperStepBarrierWorkerAck.DiscardUnknown(m)
}

var xxx_messageInfo_SuperStepBarrierWorkerAck proto.InternalMessageInfo

func (m *SuperStepBarrierWorkerAck) GetWorkerPid() *actor.PID {
	if m != nil {
		return m.WorkerPid
	}
	return nil
}

type Compute struct {
	SuperStep            uint64              `protobuf:"varint,1,opt,name=super_step,json=superStep,proto3" json:"super_step,omitempty"`
	AggregatedValues     map[string]*any.Any `protobuf:"bytes,2,rep,name=aggregated_values,json=aggregatedValues,proto3" json:"aggregated_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Compute) Reset()         { *m = Compute{} }
func (m *Compute) String() string { return proto.CompactTextString(m) }
func (*Compute) ProtoMessage()    {}
func (*Compute) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{6}
}

func (m *Compute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compute.Unmarshal(m, b)
}
func (m *Compute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compute.Marshal(b, m, deterministic)
}
func (m *Compute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compute.Merge(m, src)
}
func (m *Compute) XXX_Size() int {
	return xxx_messageInfo_Compute.Size(m)
}
func (m *Compute) XXX_DiscardUnknown() {
	xxx_messageInfo_Compute.DiscardUnknown(m)
}

var xxx_messageInfo_Compute proto.InternalMessageInfo

func (m *Compute) GetSuperStep() uint64 {
	if m != nil {
		return m.SuperStep
	}
	return 0
}

func (m *Compute) GetAggregatedValues() map[string]*any.Any {
	if m != nil {
		return m.AggregatedValues
	}
	return nil
}

type ComputeAck struct {
	VertexId             string              `protobuf:"bytes,1,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	Halted               bool                `protobuf:"varint,2,opt,name=halted,proto3" json:"halted,omitempty"`
	AggregatedValues     map[string]*any.Any `protobuf:"bytes,3,rep,name=aggregated_values,json=aggregatedValues,proto3" json:"aggregated_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ComputeAck) Reset()         { *m = ComputeAck{} }
func (m *ComputeAck) String() string { return proto.CompactTextString(m) }
func (*ComputeAck) ProtoMessage()    {}
func (*ComputeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{7}
}

func (m *ComputeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAck.Unmarshal(m, b)
}
func (m *ComputeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAck.Marshal(b, m, deterministic)
}
func (m *ComputeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAck.Merge(m, src)
}
func (m *ComputeAck) XXX_Size() int {
	return xxx_messageInfo_ComputeAck.Size(m)
}
func (m *ComputeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAck.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAck proto.InternalMessageInfo

func (m *ComputeAck) GetVertexId() string {
	if m != nil {
		return m.VertexId
	}
	return ""
}

func (m *ComputeAck) GetHalted() bool {
	if m != nil {
		return m.Halted
	}
	return false
}

func (m *ComputeAck) GetAggregatedValues() map[string]*any.Any {
	if m != nil {
		return m.AggregatedValues
	}
	return nil
}

type ComputePartitionAck struct {
	PartitionId          uint64              `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	AggregatedValues     map[string]*any.Any `protobuf:"bytes,2,rep,name=aggregated_values,json=aggregatedValues,proto3" json:"aggregated_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ComputePartitionAck) Reset()         { *m = ComputePartitionAck{} }
func (m *ComputePartitionAck) String() string { return proto.CompactTextString(m) }
func (*ComputePartitionAck) ProtoMessage()    {}
func (*ComputePartitionAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{8}
}

func (m *ComputePartitionAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputePartitionAck.Unmarshal(m, b)
}
func (m *ComputePartitionAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputePartitionAck.Marshal(b, m, deterministic)
}
func (m *ComputePartitionAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputePartitionAck.Merge(m, src)
}
func (m *ComputePartitionAck) XXX_Size() int {
	return xxx_messageInfo_ComputePartitionAck.Size(m)
}
func (m *ComputePartitionAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputePartitionAck.DiscardUnknown(m)
}

var xxx_messageInfo_ComputePartitionAck proto.InternalMessageInfo

func (m *ComputePartitionAck) GetPartitionId() uint64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *ComputePartitionAck) GetAggregatedValues() map[string]*any.Any {
	if m != nil {
		return m.AggregatedValues
	}
	return nil
}

type ComputeWorkerAck struct {
	WorkerPid            *actor.PID          `protobuf:"bytes,1,opt,name=worker_pid,json=workerPid,proto3" json:"worker_pid,omitempty"`
	AggregatedValues     map[string]*any.Any `protobuf:"bytes,2,rep,name=aggregated_values,json=aggregatedValues,proto3" json:"aggregated_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ComputeWorkerAck) Reset()         { *m = ComputeWorkerAck{} }
func (m *ComputeWorkerAck) String() string { return proto.CompactTextString(m) }
func (*ComputeWorkerAck) ProtoMessage()    {}
func (*ComputeWorkerAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{9}
}

func (m *ComputeWorkerAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeWorkerAck.Unmarshal(m, b)
}
func (m *ComputeWorkerAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeWorkerAck.Marshal(b, m, deterministic)
}
func (m *ComputeWorkerAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeWorkerAck.Merge(m, src)
}
func (m *ComputeWorkerAck) XXX_Size() int {
	return xxx_messageInfo_ComputeWorkerAck.Size(m)
}
func (m *ComputeWorkerAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeWorkerAck.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeWorkerAck proto.InternalMessageInfo

func (m *ComputeWorkerAck) GetWorkerPid() *actor.PID {
	if m != nil {
		return m.WorkerPid
	}
	return nil
}

func (m *ComputeWorkerAck) GetAggregatedValues() map[string]*any.Any {
	if m != nil {
		return m.AggregatedValues
	}
	return nil
}

type SuperStepMessage struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SuperStep            uint64   `protobuf:"varint,2,opt,name=super_step,json=superStep,proto3" json:"super_step,omitempty"`
	SrcVertexId          string   `protobuf:"bytes,3,opt,name=src_vertex_id,json=srcVertexId,proto3" json:"src_vertex_id,omitempty"`
	DestVertexId         string   `protobuf:"bytes,4,opt,name=dest_vertex_id,json=destVertexId,proto3" json:"dest_vertex_id,omitempty"`
	Message              *any.Any `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperStepMessage) Reset()         { *m = SuperStepMessage{} }
func (m *SuperStepMessage) String() string { return proto.CompactTextString(m) }
func (*SuperStepMessage) ProtoMessage()    {}
func (*SuperStepMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{10}
}

func (m *SuperStepMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperStepMessage.Unmarshal(m, b)
}
func (m *SuperStepMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperStepMessage.Marshal(b, m, deterministic)
}
func (m *SuperStepMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperStepMessage.Merge(m, src)
}
func (m *SuperStepMessage) XXX_Size() int {
	return xxx_messageInfo_SuperStepMessage.Size(m)
}
func (m *SuperStepMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperStepMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SuperStepMessage proto.InternalMessageInfo

func (m *SuperStepMessage) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SuperStepMessage) GetSuperStep() uint64 {
	if m != nil {
		return m.SuperStep
	}
	return 0
}

func (m *SuperStepMessage) GetSrcVertexId() string {
	if m != nil {
		return m.SrcVertexId
	}
	return ""
}

func (m *SuperStepMessage) GetDestVertexId() string {
	if m != nil {
		return m.DestVertexId
	}
	return ""
}

func (m *SuperStepMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type SuperStepMessageAck struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperStepMessageAck) Reset()         { *m = SuperStepMessageAck{} }
func (m *SuperStepMessageAck) String() string { return proto.CompactTextString(m) }
func (*SuperStepMessageAck) ProtoMessage()    {}
func (*SuperStepMessageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{11}
}

func (m *SuperStepMessageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperStepMessageAck.Unmarshal(m, b)
}
func (m *SuperStepMessageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperStepMessageAck.Marshal(b, m, deterministic)
}
func (m *SuperStepMessageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperStepMessageAck.Merge(m, src)
}
func (m *SuperStepMessageAck) XXX_Size() int {
	return xxx_messageInfo_SuperStepMessageAck.Size(m)
}
func (m *SuperStepMessageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperStepMessageAck.DiscardUnknown(m)
}

var xxx_messageInfo_SuperStepMessageAck proto.InternalMessageInfo

func (m *SuperStepMessageAck) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type InitPartition struct {
	PartitionId          uint64   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPartition) Reset()         { *m = InitPartition{} }
func (m *InitPartition) String() string { return proto.CompactTextString(m) }
func (*InitPartition) ProtoMessage()    {}
func (*InitPartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{12}
}

func (m *InitPartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPartition.Unmarshal(m, b)
}
func (m *InitPartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPartition.Marshal(b, m, deterministic)
}
func (m *InitPartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPartition.Merge(m, src)
}
func (m *InitPartition) XXX_Size() int {
	return xxx_messageInfo_InitPartition.Size(m)
}
func (m *InitPartition) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPartition.DiscardUnknown(m)
}

var xxx_messageInfo_InitPartition proto.InternalMessageInfo

func (m *InitPartition) GetPartitionId() uint64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

type InitPartitionAck struct {
	PartitionId          uint64   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPartitionAck) Reset()         { *m = InitPartitionAck{} }
func (m *InitPartitionAck) String() string { return proto.CompactTextString(m) }
func (*InitPartitionAck) ProtoMessage()    {}
func (*InitPartitionAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{13}
}

func (m *InitPartitionAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPartitionAck.Unmarshal(m, b)
}
func (m *InitPartitionAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPartitionAck.Marshal(b, m, deterministic)
}
func (m *InitPartitionAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPartitionAck.Merge(m, src)
}
func (m *InitPartitionAck) XXX_Size() int {
	return xxx_messageInfo_InitPartitionAck.Size(m)
}
func (m *InitPartitionAck) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPartitionAck.DiscardUnknown(m)
}

var xxx_messageInfo_InitPartitionAck proto.InternalMessageInfo

func (m *InitPartitionAck) GetPartitionId() uint64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

type ClusterInfo struct {
	WorkerInfo           []*ClusterInfo_WorkerInfo `protobuf:"bytes,1,rep,name=worker_info,json=workerInfo,proto3" json:"worker_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ClusterInfo) Reset()         { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()    {}
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{14}
}

func (m *ClusterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterInfo.Unmarshal(m, b)
}
func (m *ClusterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterInfo.Marshal(b, m, deterministic)
}
func (m *ClusterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterInfo.Merge(m, src)
}
func (m *ClusterInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterInfo.Size(m)
}
func (m *ClusterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterInfo proto.InternalMessageInfo

func (m *ClusterInfo) GetWorkerInfo() []*ClusterInfo_WorkerInfo {
	if m != nil {
		return m.WorkerInfo
	}
	return nil
}

type ClusterInfo_WorkerInfo struct {
	WorkerPid            *actor.PID `protobuf:"bytes,1,opt,name=worker_pid,json=workerPid,proto3" json:"worker_pid,omitempty"`
	Partitions           []uint64   `protobuf:"varint,2,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClusterInfo_WorkerInfo) Reset()         { *m = ClusterInfo_WorkerInfo{} }
func (m *ClusterInfo_WorkerInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterInfo_WorkerInfo) ProtoMessage()    {}
func (*ClusterInfo_WorkerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{14, 0}
}

func (m *ClusterInfo_WorkerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterInfo_WorkerInfo.Unmarshal(m, b)
}
func (m *ClusterInfo_WorkerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterInfo_WorkerInfo.Marshal(b, m, deterministic)
}
func (m *ClusterInfo_WorkerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterInfo_WorkerInfo.Merge(m, src)
}
func (m *ClusterInfo_WorkerInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterInfo_WorkerInfo.Size(m)
}
func (m *ClusterInfo_WorkerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterInfo_WorkerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterInfo_WorkerInfo proto.InternalMessageInfo

func (m *ClusterInfo_WorkerInfo) GetWorkerPid() *actor.PID {
	if m != nil {
		return m.WorkerPid
	}
	return nil
}

func (m *ClusterInfo_WorkerInfo) GetPartitions() []uint64 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type InitWorker struct {
	Partitions           []uint64 `protobuf:"varint,1,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitWorker) Reset()         { *m = InitWorker{} }
func (m *InitWorker) String() string { return proto.CompactTextString(m) }
func (*InitWorker) ProtoMessage()    {}
func (*InitWorker) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{15}
}

func (m *InitWorker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitWorker.Unmarshal(m, b)
}
func (m *InitWorker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitWorker.Marshal(b, m, deterministic)
}
func (m *InitWorker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitWorker.Merge(m, src)
}
func (m *InitWorker) XXX_Size() int {
	return xxx_messageInfo_InitWorker.Size(m)
}
func (m *InitWorker) XXX_DiscardUnknown() {
	xxx_messageInfo_InitWorker.DiscardUnknown(m)
}

var xxx_messageInfo_InitWorker proto.InternalMessageInfo

func (m *InitWorker) GetPartitions() []uint64 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type InitWorkerAck struct {
	WorkerPid            *actor.PID `protobuf:"bytes,1,opt,name=worker_pid,json=workerPid,proto3" json:"worker_pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InitWorkerAck) Reset()         { *m = InitWorkerAck{} }
func (m *InitWorkerAck) String() string { return proto.CompactTextString(m) }
func (*InitWorkerAck) ProtoMessage()    {}
func (*InitWorkerAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{16}
}

func (m *InitWorkerAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitWorkerAck.Unmarshal(m, b)
}
func (m *InitWorkerAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitWorkerAck.Marshal(b, m, deterministic)
}
func (m *InitWorkerAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitWorkerAck.Merge(m, src)
}
func (m *InitWorkerAck) XXX_Size() int {
	return xxx_messageInfo_InitWorkerAck.Size(m)
}
func (m *InitWorkerAck) XXX_DiscardUnknown() {
	xxx_messageInfo_InitWorkerAck.DiscardUnknown(m)
}

var xxx_messageInfo_InitWorkerAck proto.InternalMessageInfo

func (m *InitWorkerAck) GetWorkerPid() *actor.PID {
	if m != nil {
		return m.WorkerPid
	}
	return nil
}

type NewCluster struct {
	Workers              []*NewCluster_WorkerReq `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	NrOfPartitions       uint64                  `protobuf:"varint,2,opt,name=nr_of_partitions,json=nrOfPartitions,proto3" json:"nr_of_partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NewCluster) Reset()         { *m = NewCluster{} }
func (m *NewCluster) String() string { return proto.CompactTextString(m) }
func (*NewCluster) ProtoMessage()    {}
func (*NewCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{17}
}

func (m *NewCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCluster.Unmarshal(m, b)
}
func (m *NewCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCluster.Marshal(b, m, deterministic)
}
func (m *NewCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCluster.Merge(m, src)
}
func (m *NewCluster) XXX_Size() int {
	return xxx_messageInfo_NewCluster.Size(m)
}
func (m *NewCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCluster.DiscardUnknown(m)
}

var xxx_messageInfo_NewCluster proto.InternalMessageInfo

func (m *NewCluster) GetWorkers() []*NewCluster_WorkerReq {
	if m != nil {
		return m.Workers
	}
	return nil
}

func (m *NewCluster) GetNrOfPartitions() uint64 {
	if m != nil {
		return m.NrOfPartitions
	}
	return 0
}

type NewCluster_WorkerReq struct {
	Remote               bool     `protobuf:"varint,1,opt,name=remote,proto3" json:"remote,omitempty"`
	HostAndPort          string   `protobuf:"bytes,2,opt,name=host_and_port,json=hostAndPort,proto3" json:"host_and_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCluster_WorkerReq) Reset()         { *m = NewCluster_WorkerReq{} }
func (m *NewCluster_WorkerReq) String() string { return proto.CompactTextString(m) }
func (*NewCluster_WorkerReq) ProtoMessage()    {}
func (*NewCluster_WorkerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{17, 0}
}

func (m *NewCluster_WorkerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCluster_WorkerReq.Unmarshal(m, b)
}
func (m *NewCluster_WorkerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCluster_WorkerReq.Marshal(b, m, deterministic)
}
func (m *NewCluster_WorkerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCluster_WorkerReq.Merge(m, src)
}
func (m *NewCluster_WorkerReq) XXX_Size() int {
	return xxx_messageInfo_NewCluster_WorkerReq.Size(m)
}
func (m *NewCluster_WorkerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCluster_WorkerReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewCluster_WorkerReq proto.InternalMessageInfo

func (m *NewCluster_WorkerReq) GetRemote() bool {
	if m != nil {
		return m.Remote
	}
	return false
}

func (m *NewCluster_WorkerReq) GetHostAndPort() string {
	if m != nil {
		return m.HostAndPort
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadVertex)(nil), "LoadVertex")
	proto.RegisterType((*LoadVertexAck)(nil), "LoadVertexAck")
	proto.RegisterType((*SuperStepBarrier)(nil), "SuperStepBarrier")
	proto.RegisterType((*SuperStepBarrierAck)(nil), "SuperStepBarrierAck")
	proto.RegisterType((*SuperStepBarrierPartitionAck)(nil), "SuperStepBarrierPartitionAck")
	proto.RegisterType((*SuperStepBarrierWorkerAck)(nil), "SuperStepBarrierWorkerAck")
	proto.RegisterType((*Compute)(nil), "Compute")
	proto.RegisterMapType((map[string]*any.Any)(nil), "Compute.AggregatedValuesEntry")
	proto.RegisterType((*ComputeAck)(nil), "ComputeAck")
	proto.RegisterMapType((map[string]*any.Any)(nil), "ComputeAck.AggregatedValuesEntry")
	proto.RegisterType((*ComputePartitionAck)(nil), "ComputePartitionAck")
	proto.RegisterMapType((map[string]*any.Any)(nil), "ComputePartitionAck.AggregatedValuesEntry")
	proto.RegisterType((*ComputeWorkerAck)(nil), "ComputeWorkerAck")
	proto.RegisterMapType((map[string]*any.Any)(nil), "ComputeWorkerAck.AggregatedValuesEntry")
	proto.RegisterType((*SuperStepMessage)(nil), "SuperStepMessage")
	proto.RegisterType((*SuperStepMessageAck)(nil), "SuperStepMessageAck")
	proto.RegisterType((*InitPartition)(nil), "InitPartition")
	proto.RegisterType((*InitPartitionAck)(nil), "InitPartitionAck")
	proto.RegisterType((*ClusterInfo)(nil), "ClusterInfo")
	proto.RegisterType((*ClusterInfo_WorkerInfo)(nil), "ClusterInfo.WorkerInfo")
	proto.RegisterType((*InitWorker)(nil), "InitWorker")
	proto.RegisterType((*InitWorkerAck)(nil), "InitWorkerAck")
	proto.RegisterType((*NewCluster)(nil), "NewCluster")
	proto.RegisterType((*NewCluster_WorkerReq)(nil), "NewCluster.WorkerReq")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049) }

var fileDescriptor_213c0bb044472049 = []byte{
	// 721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xed, 0x4e, 0xdb, 0x3c,
	0x14, 0x56, 0xda, 0xf2, 0xd1, 0x13, 0x8a, 0xfa, 0x9a, 0x97, 0xf7, 0x85, 0x6e, 0x43, 0x10, 0x4d,
	0x5a, 0x41, 0x9b, 0x2b, 0x75, 0xda, 0x84, 0xf8, 0x57, 0xd8, 0x87, 0xaa, 0x31, 0xa8, 0x02, 0x02,
	0xed, 0x57, 0x14, 0x1a, 0x37, 0x44, 0x6d, 0xe3, 0xcc, 0x76, 0x60, 0xbd, 0x9b, 0x5d, 0xc2, 0xee,
	0x60, 0xb7, 0xb0, 0x0b, 0x99, 0x76, 0x0d, 0x53, 0x6c, 0x37, 0x0d, 0x59, 0xd9, 0x80, 0xfd, 0xe1,
	0x9f, 0x7d, 0xfc, 0x9c, 0x8f, 0xc7, 0xe7, 0xf1, 0x31, 0x54, 0xba, 0x74, 0x38, 0x74, 0x43, 0x0f,
	0x47, 0x8c, 0x0a, 0x5a, 0x5b, 0xf5, 0x29, 0xf5, 0x07, 0xa4, 0x21, 0x77, 0x67, 0x71, 0xaf, 0xe1,
	0x86, 0x23, 0x7d, 0xf4, 0xd2, 0x0f, 0xc4, 0x79, 0x7c, 0x86, 0xbb, 0x74, 0xd8, 0x68, 0xf1, 0x51,
	0xd8, 0x67, 0x34, 0x6c, 0x1f, 0x2b, 0xa4, 0xdb, 0x15, 0x94, 0x3d, 0xf3, 0x69, 0x43, 0x2e, 0x94,
	0x8d, 0x2b, 0x3f, 0x6b, 0x1f, 0x60, 0x9f, 0xba, 0xde, 0x09, 0x61, 0x82, 0x7c, 0x42, 0x1b, 0xb0,
	0x10, 0xb9, 0x4c, 0x04, 0x22, 0xa0, 0xa1, 0x13, 0x78, 0x2b, 0xc6, 0xba, 0x51, 0x2f, 0xd9, 0x66,
	0x6a, 0x6b, 0x7b, 0xe8, 0x01, 0x94, 0x2f, 0x24, 0x38, 0x39, 0x2f, 0xac, 0x1b, 0xf5, 0xb2, 0x3d,
	0xaf, 0x0c, 0x6d, 0xcf, 0x3a, 0x84, 0xca, 0x24, 0x5a, 0xab, 0xdb, 0xff, 0xeb, 0x80, 0xbb, 0x50,
	0x3d, 0x8a, 0x23, 0xc2, 0x8e, 0x04, 0x89, 0x76, 0x5d, 0xc6, 0x02, 0xc2, 0x10, 0x06, 0xb3, 0x3b,
	0x88, 0xb9, 0x20, 0xac, 0x1d, 0xf6, 0xa8, 0x0c, 0x69, 0x36, 0x17, 0xf0, 0xde, 0xc4, 0x66, 0x67,
	0x01, 0x56, 0x13, 0x96, 0xf2, 0x31, 0x92, 0xd2, 0xae, 0xe4, 0x35, 0x72, 0x79, 0x5b, 0xf0, 0x30,
	0xef, 0xd3, 0x19, 0xd7, 0x7c, 0x33, 0x5e, 0xd6, 0x1b, 0x58, 0xcd, 0x87, 0x38, 0xa5, 0xac, 0xaf,
	0x92, 0x6f, 0x02, 0x5c, 0xca, 0x8d, 0x13, 0x69, 0x6f, 0xb3, 0x09, 0x58, 0xf6, 0x07, 0x77, 0xda,
	0xaf, 0xec, 0xb2, 0x3a, 0xed, 0x04, 0x9e, 0xf5, 0xcd, 0x80, 0xb9, 0x3d, 0x3a, 0x8c, 0x62, 0x41,
	0xd0, 0x23, 0x00, 0x9e, 0xc4, 0x74, 0xb8, 0x20, 0x91, 0x4e, 0x5a, 0xe6, 0xe3, 0x2c, 0xe8, 0x1d,
	0xfc, 0xe3, 0xfa, 0x3e, 0x23, 0xbe, 0x2b, 0x88, 0xe7, 0x5c, 0xb8, 0x83, 0x98, 0xf0, 0x95, 0xc2,
	0x7a, 0xb1, 0x6e, 0x36, 0xd7, 0xb0, 0x8e, 0x81, 0x5b, 0x29, 0xe2, 0x44, 0x02, 0x5e, 0x87, 0x82,
	0x8d, 0xec, 0xaa, 0x9b, 0x33, 0xd7, 0x3e, 0xc0, 0xf2, 0x54, 0x28, 0xaa, 0x42, 0xb1, 0x4f, 0x46,
	0xfa, 0xca, 0x92, 0x25, 0xda, 0x82, 0x19, 0x99, 0x4c, 0xb6, 0xcf, 0x6c, 0xfe, 0x8b, 0x95, 0x4e,
	0xf1, 0x58, 0xa7, 0xb8, 0x15, 0x8e, 0x6c, 0x05, 0xd9, 0x29, 0x6c, 0x1b, 0xd6, 0x77, 0x03, 0x40,
	0x97, 0xf3, 0xa7, 0x4e, 0xa0, 0xff, 0x60, 0xf6, 0xdc, 0x1d, 0x08, 0xa2, 0xb4, 0x31, 0x6f, 0xeb,
	0x1d, 0x3a, 0x98, 0xc6, 0xb5, 0x28, 0xb9, 0x6e, 0xe0, 0x49, 0xf0, 0x7b, 0x42, 0x77, 0x49, 0x57,
	0x74, 0x4b, 0x11, 0xa1, 0xd3, 0xeb, 0x3b, 0xba, 0x85, 0xa7, 0xc4, 0xbc, 0x0f, 0x74, 0x7f, 0x18,
	0x50, 0xd5, 0xa5, 0xdd, 0x45, 0xf0, 0xe8, 0xf8, 0x7a, 0xce, 0x4f, 0x70, 0x3e, 0xf0, 0x7d, 0x20,
	0xfc, 0xd5, 0xc8, 0x4c, 0xa9, 0xf7, 0x84, 0x73, 0xd7, 0x27, 0x08, 0x41, 0x29, 0x8e, 0x53, 0x3d,
	0xcb, 0x75, 0xee, 0xf9, 0x16, 0xf2, 0xcf, 0xd7, 0x82, 0x0a, 0x67, 0x5d, 0x67, 0xf2, 0x16, 0x8a,
	0xd2, 0xd7, 0xe4, 0xac, 0x7b, 0x32, 0x7e, 0x0e, 0x8f, 0x61, 0xd1, 0x23, 0x5c, 0x64, 0x40, 0x25,
	0x09, 0x5a, 0x48, 0xac, 0x29, 0x0a, 0xc3, 0xdc, 0x50, 0xd5, 0xb1, 0x32, 0xf3, 0x1b, 0x0e, 0x63,
	0x90, 0xb5, 0x99, 0x19, 0x91, 0x9a, 0x40, 0xd2, 0xb4, 0x29, 0x1c, 0xac, 0x26, 0x54, 0xda, 0x61,
	0x20, 0x52, 0xd1, 0xdd, 0x64, 0x14, 0xbe, 0x80, 0xea, 0x15, 0x9f, 0x1b, 0x4e, 0xd0, 0xcf, 0x06,
	0x98, 0x99, 0xa9, 0x8e, 0xb6, 0xc1, 0xd4, 0x1a, 0x0a, 0xd4, 0xe0, 0x4f, 0x24, 0xf1, 0x7f, 0x76,
	0xf0, 0x63, 0xa5, 0x0b, 0xf9, 0x07, 0x68, 0xbd, 0x25, 0xeb, 0xda, 0x29, 0xc0, 0xe4, 0xe4, 0x36,
	0x5a, 0x5c, 0x03, 0x48, 0x2b, 0x52, 0x22, 0x2c, 0xd9, 0x19, 0x8b, 0xf5, 0x14, 0x20, 0x61, 0xa6,
	0x82, 0xe7, 0xd0, 0xc6, 0x2f, 0xe8, 0x1d, 0x75, 0x77, 0x77, 0xfa, 0x06, 0xbe, 0x18, 0x00, 0x07,
	0xe4, 0x52, 0x93, 0x45, 0x0d, 0x98, 0x53, 0x67, 0x5c, 0xdf, 0xc3, 0x32, 0x9e, 0x9c, 0xea, 0x6b,
	0xb0, 0xc9, 0x47, 0x7b, 0x8c, 0x42, 0x75, 0xa8, 0x86, 0xcc, 0xa1, 0x3d, 0xe7, 0x0a, 0x9f, 0xe4,
	0xce, 0x17, 0x43, 0x76, 0xd8, 0x4b, 0x7b, 0xc3, 0x6b, 0x6f, 0xa1, 0x9c, 0xfa, 0x27, 0xe3, 0x97,
	0x91, 0x21, 0x15, 0x44, 0x56, 0x37, 0x6f, 0xeb, 0x5d, 0xa2, 0xd5, 0x73, 0xca, 0x85, 0xe3, 0x86,
	0x9e, 0x13, 0x51, 0x26, 0xf4, 0xcf, 0x6d, 0x26, 0xc6, 0x56, 0xe8, 0x75, 0x28, 0x13, 0x67, 0xb3,
	0x52, 0x6c, 0xcf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x98, 0x89, 0x25, 0x54, 0xc6, 0x08, 0x00,
	0x00,
}
