// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aggregator.proto

package aggregator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VertexStats struct {
	ActiveVertices       uint64   `protobuf:"varint,1,opt,name=active_vertices,json=activeVertices,proto3" json:"active_vertices,omitempty"`
	TotalVertices        uint64   `protobuf:"varint,2,opt,name=total_vertices,json=totalVertices,proto3" json:"total_vertices,omitempty"`
	MessagesSent         uint64   `protobuf:"varint,3,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VertexStats) Reset()         { *m = VertexStats{} }
func (m *VertexStats) String() string { return proto.CompactTextString(m) }
func (*VertexStats) ProtoMessage()    {}
func (*VertexStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{0}
}

func (m *VertexStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VertexStats.Unmarshal(m, b)
}
func (m *VertexStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VertexStats.Marshal(b, m, deterministic)
}
func (m *VertexStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VertexStats.Merge(m, src)
}
func (m *VertexStats) XXX_Size() int {
	return xxx_messageInfo_VertexStats.Size(m)
}
func (m *VertexStats) XXX_DiscardUnknown() {
	xxx_messageInfo_VertexStats.DiscardUnknown(m)
}

var xxx_messageInfo_VertexStats proto.InternalMessageInfo

func (m *VertexStats) GetActiveVertices() uint64 {
	if m != nil {
		return m.ActiveVertices
	}
	return 0
}

func (m *VertexStats) GetTotalVertices() uint64 {
	if m != nil {
		return m.TotalVertices
	}
	return 0
}

func (m *VertexStats) GetMessagesSent() uint64 {
	if m != nil {
		return m.MessagesSent
	}
	return 0
}

func init() {
	proto.RegisterType((*VertexStats)(nil), "VertexStats")
}

func init() { proto.RegisterFile("aggregator.proto", fileDescriptor_60785b04c84bec7e) }

var fileDescriptor_60785b04c84bec7e = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4c, 0x4f, 0x2f,
	0x4a, 0x4d, 0x4f, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x6a, 0x62, 0xe4,
	0xe2, 0x0e, 0x4b, 0x2d, 0x2a, 0x49, 0xad, 0x08, 0x2e, 0x49, 0x2c, 0x29, 0x16, 0x52, 0xe7, 0xe2,
	0x4f, 0x4c, 0x2e, 0xc9, 0x2c, 0x4b, 0x8d, 0x2f, 0x4b, 0x2d, 0x2a, 0xc9, 0x4c, 0x4e, 0x2d, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0xe2, 0x83, 0x08, 0x87, 0x41, 0x45, 0x85, 0x54, 0xb9, 0xf8,
	0x4a, 0xf2, 0x4b, 0x12, 0x73, 0x10, 0xea, 0x98, 0xc0, 0xea, 0x78, 0xc1, 0xa2, 0x70, 0x65, 0xca,
	0x5c, 0xbc, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0xf1, 0xc5, 0xa9, 0x79, 0x25, 0x12,
	0xcc, 0x60, 0x55, 0x3c, 0x30, 0xc1, 0xe0, 0xd4, 0xbc, 0x92, 0x24, 0x36, 0xb0, 0x5b, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x8a, 0xfc, 0xa5, 0x9f, 0x00, 0x00, 0x00,
}
